import { Client } from "@/types/client";
export const clientsData: Client[] = [
  {
    id: 1,
    title: "",
    logo: "https://i.postimg.cc/PJLYjkZH/Oswaal-Books-Logo.avif",
    logoWhite: "/images/brands/arc-ptv-logo.svg",
    link: "https://oswaal.ai/",
    showTextWithLogo: true,
  },
  {
    id: 2,
    title: "",
    logo: "https://ik.imagekit.io/afza1fjxz/Zryth%20Solutions%20Brands/trivize.avif",
    logoWhite: "/images/brands/triwize-logo.svg",
    link: "https://www.triwize.com/",
    showTextWithLogo: true,
  },
  {
    id: 3,
    title: "",
    logo: "https://ik.imagekit.io/afza1fjxz/Zryth%20Solutions%20Brands/digital_chacha.webp",
    logoWhite: "/images/brands/digitalchacha-logo.svg",
    link: "https://digitalchacha.com/",
    showTextWithLogo: true,
  },
  {
    id: 4,
    title: "",
    logo: "https://ik.imagekit.io/afza1fjxz/Zryth%20Solutions%20Brands/anuyog-logo.png",
    logoWhite: "/images/brands/anuyog-logo.svg",
    link: "https://anuyogsoftwares.com/",
    showTextWithLogo: true,
  },
  {
    id: 5,
    title: "",
    logo: "https://i.postimg.cc/wvY923mD/dimple.avif",
    logoWhite: "/images/brands/dimple-logo.svg",
    link: "https://www.dimplecollection.in/?srsltid=AfmBOoqHGuBycBmHaE6-pKwuSYIRr4fee47bgm1sGuKpqDoZcM-rBi_h",
    showTextWithLogo: true,
  },
  {
    id: 6,
    title: "",
    logo: "https://ik.imagekit.io/afza1fjxz/Zryth%20Solutions%20Brands/agra_rollers.png",
    logoWhite: "https://i.postimg.cc/526jGdQb/agra-rollers.png",
    link: "https://www.agraroller.com/",
    showTextWithLogo: true,
  },
  {
    id: 7,
    title: "",
    logo: "https://i.postimg.cc/tg1R6J4z/logo-(1).jpg",
    logoWhite: "https://i.postimg.cc/tg1R6J4z/logo-(1).jpg",
    link: "https://rahiseva.com/",
    showTextWithLogo: true,
  },
  {
    id: 8,
    title: "",
    logo: "https://ik.imagekit.io/afza1fjxz/Zryth%20Solutions%20Brands/pbpd_logo.jpg",
    logoWhite: "https://ik.imagekit.io/afza1fjxz/Zryth%20Solutions%20Brands/pbpd_logo.jpg",
    link: "https://www.sahityabhawan.com/",
    showTextWithLogo: true,
  }
];
