import { Client } from "@/types/client";
export const clientsData: Client[] = [
  {
    id: 1,
    title: "Triwize",
    logo: "https://i.postimg.cc/htfhwWQW/trivize.avif",
    logoWhite: "/images/brands/triwize-logo.svg",
    link: "https://www.triwize.com/",
    showTextWithLogo: true,
  },
  {
    id: 2,
    title: "Digital Chacha",
    logo: "https://i.postimg.cc/qM93VYjF/digital_chacha.webp",
    logoWhite: "/images/brands/digitalchacha-logo.svg",
    link: "https://digitalchacha.com/",
    showTextWithLogo: true,
  },
  {
    id: 3,
    title: "Anuyog Software",
    logo: "https://i.postimg.cc/PrBwsc29/anuyog_logo.png",
    logoWhite: "/images/brands/anuyog-logo.svg",
    link: "https://anuyogsoftwares.com/",
    showTextWithLogo: true,
  },
  {
    id: 4,
    title: "Dimple Collection",
    logo: "https://i.postimg.cc/wvY923mD/dimple.avif",
    logoWhite: "/images/brands/dimple-logo.svg",
    link: "https://www.dimplecollection.in/?srsltid=AfmBOoqHGuBycBmHaE6-pKwuSYIRr4fee47bgm1sGuKpqDoZcM-rBi_h",
    showTextWithLogo: true,
  },
  {
    id: 5,
    title: "Agra Rollers",
    logo: "https://i.postimg.cc/526jGdQb/agra-rollers.png",
    logoWhite: "https://i.postimg.cc/526jGdQb/agra-rollers.png",
    link: "https://www.agraroller.com/",
    showTextWithLogo: true,
  },
  {
    id: 6,
    title: "Rai seva",
    logo: "https://i.postimg.cc/DwsDhS3H/drive.jpg",
    logoWhite: "https://i.postimg.cc/JhD396k0/ARC-Ptv-Ltd-Logo.avif",
    link: "#",
    showTextWithLogo: true,
  },

  {
    id: 7,
    title: "Oswaal Books",
    logo: "https://i.postimg.cc/PJLYjkZH/Oswaal-Books-Logo.avif",
    logoWhite: "/images/brands/arc-ptv-logo.svg",
    link: "https://oswaal.ai/",
    showTextWithLogo: true,
  },
];
